Sprint 1
Jane2727/middle.messenger.praktikum.yandex pull request #1
Opened 2021-08-26 20:37 UTC by Jane2727

2021-08-28 11:18 UTC, nickchamel requested changes
Привет. Отличная работа, молодец! Единственное чего не хватает, это
![image](https://user-images.githubusercontent.com/28347933/131216218-60c34c3f-a821-499c-9eea-4186fcf6dcc3.png)
Давай доделаем это и можно будет двигаться дальше

2021-08-28 11:18 UTC, nickchamel commented on .gitignore
> +*.lock
На проекте может использоваться yarn, он создает файл yarn.lock
Его лучше не игнорить, тут можно почитать почему
https://classic.yarnpkg.com/en/docs/yarn-lock/#toc-check-into-source-control

2021-08-28 11:18 UTC, nickchamel commented on package.json
> +    "dev": "parcel index.html --port 3000 --no-cache --open && node server.js",
получается что так ты запустишь и парселевскую watch-сборку и экспресс-сервер. Достаточно будет 1ого
Экспресс нужен только локально для раздачи статики из билда (dist)
Еще момент - я не вижу у тебя server.js в принципе, а он должен быть)

2021-08-28 11:18 UTC, nickchamel commented on src/components/button/button.js
> +    const template = Handlebars.compile(buttonTemplate);
Эту конструкцию можно вынести наверх перед объявлением компонента, поскольку `Handlebars.compile(buttonTemplate)` всегда вернет один и тот же результат, то нет необходимости делать это каждый раз, когда мы будем создавать компонент

2021-08-28 11:18 UTC, nickchamel commented on src/components/input/input.js
> +        disabledInput: disabled || null,
ты можешь выше указать дефолтные значения для этих пропсов
```
const {
  isProfileInput,
  required = false,
  value = null,
  disabled = false,
  inputContainerClassName,
  inputClassName,
} = params;
```
Для disabled кстати тоже правильней будет boolean использовать
И тогда здесь будет просто:
```
    const context = { 
        ...params, 
        required,
        value,
        disabledInput: disabled,
```
Это хорошая практика, потому что если дальше по коду эти переменные будут использоваться в нескольких местах, то не нужно будет в каждом месте указывать дефолтное значение

2021-08-28 11:18 UTC, nickchamel commented on src/index.js
> +    notFound: errorPage(routes.notFound)
Править это необязательно, это тебе комментарий на будущее, из собственного опыта:
(Чаще всего) лучше делать отдельные страницы и отдельные компоненты (то есть отдельно loginPage, registrationPage и тд)
Поначалу всегда кажется - "Да эти компоненты идентичны, там только в одном месте разница, поэтому это будет один но с условием", а потом это все растет, растет, бизнес-требования меняются, условия дополняютcя, и компонент, который должен был быть призван упростить код, растет как на дрожжях и поддерживать его уже невозможно.
Понятное дело, что здесь ограниченный функционал с конкретной логикой, поэтому здесь ты вряд ли столкнешься с такой проблемой, поэтому это тебе рекомендация на будущее)

2021-08-29 09:46 UTC, Jane2727 commented on package.json
> +    "dev": "parcel index.html --port 3000 --no-cache --open && node server.js",
спасибо! действительно в процессе разработки потерялся файлик, вернула его на место) 
и убрала доп.вызов из dev запуска

2021-08-29 09:49 UTC, Jane2727 commented on src/components/input/input.js
> +        disabledInput: disabled || null,
спасибо за совет) так код выглядит более лаконичным

2021-08-29 09:50 UTC, Jane2727 commented on src/index.js
> +    notFound: errorPage(routes.notFound)
В будущем постараюсь этого придерживаться. Спасибо за ревью!

2021-08-29 10:37 UTC, nickchamel commented
Отлично. Работу принял. Успехов в дальнейшем!

2021-08-29 10:40 UTC, merged